/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import OperateTarget.Employee;
import Util.*;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JDesktopPane;

/**
 *
 * @author cong's pc
 */
public class MainFrame extends javax.swing.JFrame {
    public static Employee user = LoginFrame.user;
    /**
     * Creates new form ProviewFrame
     */
    public MainFrame() {
        initComponents();
         //将多文档容器设置为主窗体的内容面板
       // this.setContentPane(mainDeskPane1);
        LocationUtil.setFullScreen(this);
        if(user.getElevel() == 1){
            this.setTitle(user.getEname() + " " + "管理员");
        }else {
            this.setTitle(user.getEname() + " " + "普通用户");
            this.itemEmployee.setEnabled(false);
            this.itemPurchaseInStore.setEnabled(false);

            this.itemPurchaseSearch.setEnabled(false);
            this.itemSupplier.setEnabled(false);
            this.itemSupplierDeal.setEnabled(false);
            this.itemSProductInOut.setEnabled(false);
            this.itemSProductPurchase.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mainFrameBGPanel1 = new view.MainFrameBGPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemSupplier = new javax.swing.JMenuItem();
        itemProduct = new javax.swing.JMenuItem();
        itemEmployee = new javax.swing.JMenuItem();
        itemCustomer = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemPurchaseSearch = new javax.swing.JMenuItem();
        itemPurchaseInStore = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        itemSupplierDeal = new javax.swing.JMenuItem();
        itemCustomerDeal = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        itemSProductPurchase = new javax.swing.JMenuItem();
        itemSProductSell = new javax.swing.JMenuItem();
        itemSProductInOut = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout mainFrameBGPanel1Layout = new javax.swing.GroupLayout(mainFrameBGPanel1);
        mainFrameBGPanel1.setLayout(mainFrameBGPanel1Layout);
        mainFrameBGPanel1Layout.setHorizontalGroup(
            mainFrameBGPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1493, Short.MAX_VALUE)
        );
        mainFrameBGPanel1Layout.setVerticalGroup(
            mainFrameBGPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );

        jMenu1.setText("供应及采购管理");

        itemSupplier.setText("供应商");
        itemSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSupplierActionPerformed(evt);
            }
        });
        jMenu1.add(itemSupplier);

        itemProduct.setText("商品信息");
        itemProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProductActionPerformed(evt);
            }
        });
        jMenu1.add(itemProduct);

        itemEmployee.setText("员工管理");
        itemEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEmployeeActionPerformed(evt);
            }
        });
        jMenu1.add(itemEmployee);

        itemCustomer.setText("顾客列表管理");
        itemCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCustomerActionPerformed(evt);
            }
        });
        jMenu1.add(itemCustomer);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("采购管理");

        itemPurchaseSearch.setText("采购查询");
        itemPurchaseSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPurchaseSearchActionPerformed(evt);
            }
        });
        jMenu2.add(itemPurchaseSearch);

        itemPurchaseInStore.setText("采购入库");
        itemPurchaseInStore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPurchaseInStoreActionPerformed(evt);
            }
        });
        jMenu2.add(itemPurchaseInStore);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("统计查询");

        jMenu7.setText("交易统计");

        itemSupplierDeal.setText("供应商交易统计");
        itemSupplierDeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSupplierDealActionPerformed(evt);
            }
        });
        jMenu7.add(itemSupplierDeal);

        itemCustomerDeal.setText("客户交易统计");
        itemCustomerDeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCustomerDealActionPerformed(evt);
            }
        });
        jMenu7.add(itemCustomerDeal);

        jMenu5.add(jMenu7);

        jMenu6.setText("单件商品相关查询");

        itemSProductPurchase.setText("单件商品采购表");
        itemSProductPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSProductPurchaseActionPerformed(evt);
            }
        });
        jMenu6.add(itemSProductPurchase);

        itemSProductSell.setText("单件商品销售表");
        itemSProductSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSProductSellActionPerformed(evt);
            }
        });
        jMenu6.add(itemSProductSell);

        itemSProductInOut.setText("单件商品进出表");
        itemSProductInOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSProductInOutActionPerformed(evt);
            }
        });
        jMenu6.add(itemSProductInOut);

        jMenu5.add(jMenu6);

        jMenuBar1.add(jMenu5);

        jMenu3.setText("  记录查询");

        jMenuItem5.setText("查询仓库");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem2.setText("查询货架");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("查询销售");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("查询库存转移");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu8.setText("  销售");
        jMenu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu8ActionPerformed(evt);
            }
        });

        jMenuItem6.setText("售货");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem6);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainFrameBGPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainFrameBGPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void itemProductActionPerformed(java.awt.event.ActionEvent evt) {                                            
         showFrame(GoodsADCS.class);
    }                                           

    private void itemCustomerActionPerformed(java.awt.event.ActionEvent evt) {                                             
        showFrame(CustomerADCS.class);
    }                                            

    private void itemSupplierActionPerformed(java.awt.event.ActionEvent evt) {                                             
       showFrame(SupplierADCS.class);
    }                                            

    private void itemEmployeeActionPerformed(java.awt.event.ActionEvent evt) {                                             
      showFrame(EmployeeADCS.class);
    }                                            

    private void itemPurchaseSearchActionPerformed(java.awt.event.ActionEvent evt) {                                                   
            showFrame(AllPurchase.class);
    }                                                  

    private void itemPurchaseInStoreActionPerformed(java.awt.event.ActionEvent evt) {                                                    
            showFrame(PurchaseToStore.class);
    }                                                   

    private void itemSProductInOutActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        showFrame(SingleTransfer.class);
    }                                                 

    private void itemSProductSellActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        showFrame(SingleSellSearch.class);
    }                                                

    private void itemSProductPurchaseActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        showFrame(SinglePurchaseSearch.class);
    }                                                    

    private void itemCustomerDealActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        showFrame(CustomerSellRecord.class);
    }                                                

    private void itemSupplierDealActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        showFrame(SupplyRecord.class);
    }                                                

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        showFrame(BaseADCS.class);
    }                                          

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        showFrame(RackADCS.class);
    }                                          

    private void jMenu8ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        showFrame(SellFrame.class);
    }                                      

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        showFrame(SellRecord.class);
    }                                          

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        showFrame(AllTransfer.class);
    }                                          

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        showFrame(SellFrame.class);
    }                                          
     //显示内部窗体的公共方法
    public void showFrame(Class clazz){
        //打开商品管理内部窗体
        //1产生 对象
        JInternalFrame frame = FrameUtil.buildFrame(clazz);
         //2桌面容器先删除
        this.mainFrameBGPanel1.remove(frame);
        //3再添加
        this.mainFrameBGPanel1.add(frame);
         //4显示
        LocationUtil.setScreenCenter(frame);
        frame.setVisible(true);
         //5显示在最前
        frame.toFront();
        try {
              //6处于选中状态
            frame.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JMenuItem itemCustomer;
    private javax.swing.JMenuItem itemCustomerDeal;
    private javax.swing.JMenuItem itemEmployee;
    private javax.swing.JMenuItem itemProduct;
    private javax.swing.JMenuItem itemPurchaseInStore;
    private javax.swing.JMenuItem itemPurchaseSearch;
    private javax.swing.JMenuItem itemSProductInOut;
    private javax.swing.JMenuItem itemSProductPurchase;
    private javax.swing.JMenuItem itemSProductSell;
    private javax.swing.JMenuItem itemSupplier;
    private javax.swing.JMenuItem itemSupplierDeal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private view.MainFrameBGPanel mainFrameBGPanel1;
    // End of variables declaration                   
}
