/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Biz.BaseStoreBiz;
import Biz.BaseStoreBizImpl;
import Biz.PurchaseBiz;
import Biz.PurchaseBizImpl;
import Dao.DBLink;
import OperateTarget.BaseStore;
import OperateTarget.Purchase;
import Util.*;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class PurchaseFrame extends javax.swing.JInternalFrame {
     //����biz
    PurchaseBiz pbiz = new PurchaseBizImpl();
    BaseStoreBiz bbiz = new BaseStoreBizImpl();
    private Object JoptionPane;
    /**
     * Creates new form ProductFrame
     */
    public PurchaseFrame() {
        initComponents();
        //��ʼ�������ɾ����ť��ť
        this.btnAct.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jComboBox4 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtEid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtGnum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSdate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSid = new javax.swing.JTextField();
        btnAct = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtCondition = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setTitle("��Ʒ�ɹ�");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ա�����", "��Ʒ���", "��Ӧ�̱��", "��Ʒ����", "��������"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduct);

        jLabel2.setText("Ա�����");

        jLabel10.setForeground(new java.awt.Color(255, 51, 51));

        jLabel4.setText("��Ʒ����");

        jLabel6.setText("��Ʒ���");

        jLabel8.setText("��������");

        txtSdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSdateActionPerformed(evt);
            }
        });

        jLabel9.setText("��Ӧ�̱��");

        txtSid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtGnum, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(194, 194, 194))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtEid, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtGid, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSdate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtSid, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtSid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtGid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtEid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtSdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtGnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        btnAct.setText("����");
        btnAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActActionPerformed(evt);
            }
        });

        btnExit.setText("�˳�");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnSearch.setText("��ѯ");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnSearch))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExit)))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAct)
                    .addComponent(btnExit))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void tblProductMouseClicked(java.awt.event.MouseEvent evt) {                                        
        //���ѡ��ĳ�У�������Ϣ��ʾ��������
        int row = this.tblProduct.getSelectedRow();
        //����row��ȡÿ�е�ֵ
        this.txtEid.setText(this.tblProduct.getValueAt(row, 0)+"");
        this.txtGid.setText(this.tblProduct.getValueAt(row, 1)+"");
        this.txtSid.setText(this.tblProduct.getValueAt(row, 2) + "");
        this.txtGnum.setText(this.tblProduct.getValueAt(row, 3)+"");
        this.txtSdate.setText(this.tblProduct.getValueAt(row, 4)+"");
        //����ɾ����ť����
        this.btnAct.setEnabled(true);

    }                                       

    private void btnActActionPerformed(java.awt.event.ActionEvent evt) {                                   
        //1��ȡ��Ʒ��Ϣ
        SimpleDateFormat fdt = new SimpleDateFormat("yy-mm-dd");
        int eid = Integer.parseInt(this.txtEid.getText());
        int gid = Integer.parseInt(this.txtGid.getText());
        int sid = Integer.parseInt(this.txtSid.getText());
        int gnum = Integer.parseInt(this.txtGnum.getText());
        Date dt = null;
        try {
            dt = fdt.parse(this.txtSdate.getText());
        } catch (ParseException ex) {
            Logger.getLogger(PurchaseFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    //���ݸ�ʽ��֤ʹ��StringUtil
        //1��֤�ǿ�
        try{
            if(eid == 0){
                JOptionPane.showMessageDialog(this, "�ֿ���Ϊ��");
                return;
            }
            if(gid == 0){
                JOptionPane.showMessageDialog(this, "�ֿ���Ϊ��");
                return;
            }
            if(sid == 0){
                JOptionPane.showMessageDialog(this, "�ֿ���Ϊ��");
                return;
            }
            if(gnum == 0){
                JOptionPane.showMessageDialog(this, "�ֿ���Ϊ��");
                return;
            }
            if(dt == null){
                JOptionPane.showMessageDialog(this, "�ֿ���Ϊ��");
                return;
            }
        }catch(Exception e){
            return;
        }
        boolean result = false;
        DBLink lk = new DBLink();
        Connection conn = lk.getConnection();
        BaseStore p = new BaseStore();
        Purchase t  = new Purchase();
        p.setBid(sid);
        p.setGid(gid);
        p.setGnum(gnum);
        t.setEid(eid);
        t.setGid(gid);
        t.setSid(sid);
        t.setGnum(gnum);
        t.setPurdate(dt);
        try {
            result = pbiz.update(conn, t);
            result = bbiz.update(conn, p);
        } catch (SQLException ex) {
            Logger.getLogger(PurchaseFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(result == true){
            JOptionPane.showMessageDialog(this, "�޸ĳɹ�");
            List<Purchase> listp = pbiz.findAll();
            List<BaseStore> listb = bbiz.findAll();
            showOnTable(listp,listb);
        }else{
            JOptionPane.showMessageDialog(this, "�޸�ʧ��");
        }
        //��������Ϣ
        clearInput();
    }                                  

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {                                        
      this.dispose();
    }                                       

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {                                          
        //ģ����ѯ
        String condition = this.txtCondition.getText().trim();
        List<BaseStore> listb = bbiz.findByCondition(condition, 0);
        List<Purchase> listp = pbiz.findByCondition(condition, 0);
        showOnTable(listp,listb);
    }                                         

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {                                         
         FrameUtil.framemap.remove(PurchaseFrame.class.getName());
    }                                        

    private void txtSdateActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void txtSidActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      
     public void clearInput(){
        this.txtEid.setText("");

    }
    public void showOnTable(List<Purchase> listp,List<BaseStore> listb){
        //��ȡ�ƶ���tblProduct�����ģ��
        DefaultTableModel dtm = (DefaultTableModel) this.tblProduct.getModel();
        //2��ձ����Ϣ
        while(dtm.getRowCount()>0){
            dtm.removeRow(0);
        }
        //��ʾ����
        for(BaseStore q  : listb){
        for(Purchase p : listp){
            //��ɫ����
            if(q.getGid() == p.getGid()){
            Vector vt = new Vector();
            vt.add(p.getEid());
            vt.add(p.getGid());
            vt.add(p.getSid());
            vt.add(p.getGnum());
            vt.add(p.getPurdate());
            dtm.addRow(vt);
            }
        }
        }
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTextField txtCondition;
    private javax.swing.JTextField txtEid;
    private javax.swing.JTextField txtGid;
    private javax.swing.JTextField txtGnum;
    private javax.swing.JTextField txtSdate;
    private javax.swing.JTextField txtSid;
    private javax.swing.JButton btnAct;
    // End of variables declaration                   
}
