/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Biz.BaseBiz;
import Biz.BaseBizImpl;
import Biz.BaseStoreBiz;
import Biz.BaseStoreBizImpl;
import Biz.PurchaseBiz;
import Biz.PurchaseBizImpl;
import Dao.DBLink;
import OperateTarget.BaseStore;
import OperateTarget.Purchase;
import Util.*;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class PurchaseToStore extends javax.swing.JInternalFrame {
     //引入biz
    PurchaseBiz pbiz = new PurchaseBizImpl();
    BaseBiz bbiz = new BaseBizImpl();
    BaseStoreBiz bsbiz = new BaseStoreBizImpl();
    private Object JoptionPane;
    /**
     * Creates new form ProductFrame
     */
    public PurchaseToStore() {
        initComponents();
        //初始化保存和删除按钮按钮
        this.btnSave.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jComboBox4 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtEid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtGnum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtBid = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        txtCondition = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setTitle("采购入库");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "员工编号", "商品编号", "供应商编号", "商品数量", "购入日期", "存放仓库"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduct);

        jLabel2.setText("员工编号");

        jLabel10.setForeground(new java.awt.Color(255, 51, 51));

        jLabel4.setText("商品数量");

        jLabel6.setText("商品编号");

        jLabel8.setText("购入日期");

        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        jLabel9.setText("供应商编号");

        txtPid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPidActionPerformed(evt);
            }
        });

        jLabel11.setText("存放仓库");

        txtBid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtGnum, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(194, 194, 194))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtEid, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtGid, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPid, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtBid, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(50, 50, 50))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtPid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtGid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtEid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtBid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtGnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        btnSave.setText("保存");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("取消");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnExit.setText("退出");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnAdd.setText("新增");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSearch.setText("查询");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(553, 553, 553)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnSearch)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnSave)
                    .addComponent(btnCancel)
                    .addComponent(btnExit))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void tblProductMouseClicked(java.awt.event.MouseEvent evt) {                                        
        //鼠标选中某行，改行信息显示到输出面板
        int row = this.tblProduct.getSelectedRow();
        //根据row获取每列的值
        this.txtEid.setText(this.tblProduct.getValueAt(row, 0)+"");

        //保存删除按钮可用
        this.btnSave.setEnabled(true);

    }                                       

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {                                       
        //1获取商品信息
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd ");
        int bid = Integer.parseInt(this.txtBid.getText());
        int eid = Integer.parseInt(this.txtEid.getText());
        int gid = Integer.parseInt(this.txtGid.getText());
        int gnum = Integer.parseInt(this.txtGnum.getText());
        int sid = Integer.parseInt(this.txtPid.getText());
        Date dt = null;
        try {
            dt = sdf.parse(this.txtDate.getText());
        } catch (ParseException ex) {
            Logger.getLogger(PurchaseToStore.class.getName()).log(Level.SEVERE, null, ex);
        }
        //数据格式验证使用StringUtil
        //1验证非空
        try{
                        if(bid == 0){
                JOptionPane.showMessageDialog(this, "仓库编号为空");
                return;
            }
            if(eid == 0){
                JOptionPane.showMessageDialog(this, "仓库编号为空");
                return;
            }
            if(gid == 0){
                JOptionPane.showMessageDialog(this, "仓库编号为空");
                return;
            }
            if(sid == 0){
                JOptionPane.showMessageDialog(this, "仓库编号为空");
                return;
            }
            if(gnum == 0){
                JOptionPane.showMessageDialog(this, "仓库编号为空");
                return;
            }
            if(dt == null){
                JOptionPane.showMessageDialog(this, "仓库编号为空");
                return;
            }
        }catch(Exception e){
            return;
        }

        DBLink lk = new DBLink();
        Connection conn = lk.getConnection();
        boolean result = false;
        BaseStore p = new BaseStore();
        Purchase t = new Purchase();
        t.setEid(eid);
        t.setGid(gid);
        t.setSid(sid);
        p.setBid(bid);
        p.setGid(gid);
        p.setGnum(gnum);
        t.setPurdate(dt);
        try {
            result = bsbiz.add(conn,p);
            result = pbiz.add(conn, t);
        } catch (SQLException ex) {
            Logger.getLogger(PurchaseToStore.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try {
                conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(PurchaseToStore.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(result == true){
            JOptionPane.showMessageDialog(this, "添加成功");
            List<Purchase>listp = pbiz.findAll();
            List<BaseStore> listb = bsbiz.findAll();
            showOnTable(listp,listb);
        }else{
            JOptionPane.showMessageDialog(this, "添加失败");
        }
        //清空面板信息
        clearInput();
    }                                      

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {                                        
        //1获取商品信息
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd ");
        int bid = Integer.parseInt(this.txtBid.getText());
        int eid = Integer.parseInt(this.txtEid.getText());
        int gid = Integer.parseInt(this.txtGid.getText());
        int gnum = Integer.parseInt(this.txtGnum.getText());
        int sid = Integer.parseInt(this.txtPid.getText());
        Date dt = null;
        try {
            dt = sdf.parse(this.txtDate.getText());
        } catch (ParseException ex) {
            Logger.getLogger(PurchaseToStore.class.getName()).log(Level.SEVERE, null, ex);
        }
        //数据格式验证使用StringUtil
        //1验证非空
        try{
            if(bid == 0){
                JOptionPane.showMessageDialog(this, "仓库编号为空");
                return;
            }
            if(eid == 0){
                JOptionPane.showMessageDialog(this, "仓库编号为空");
                return;
            }
            if(gid == 0){
                JOptionPane.showMessageDialog(this, "仓库编号为空");
                return;
            }
            if(sid == 0){
                JOptionPane.showMessageDialog(this, "仓库编号为空");
                return;
            }
            if(gnum == 0){
                JOptionPane.showMessageDialog(this, "仓库编号为空");
                return;
            }
            if(dt == null){
                JOptionPane.showMessageDialog(this, "仓库编号为空");
                return;
            }
        }catch(Exception e){
            return;
        }
        DBLink lk = new DBLink();
        Connection conn = lk.getConnection();
        boolean result = false;

        BaseStore p = new BaseStore();
        Purchase t = new Purchase();
        t.setEid(eid);
        t.setGid(gid);
        t.setSid(sid);
        p.setBid(bid);
        p.setGid(gid);
        p.setGnum(gnum);
        t.setPurdate(dt);
        try {
            result = bsbiz.add(conn,p);
            result = pbiz.add(conn, t);
        } catch (SQLException ex) {
            Logger.getLogger(PurchaseToStore.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try {
                conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(PurchaseToStore.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(result == true){
            JOptionPane.showMessageDialog(this, "添加成功");
            List<Purchase>listp = pbiz.findAll();
            List<BaseStore> listb = bsbiz.findAll();
            showOnTable(listp,listb);
        }else{
            JOptionPane.showMessageDialog(this, "添加失败");
        }
        //清空面板信息
        clearInput();
    }                                       

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {                                          
        //界面恢复到最初状态
        clearInput();
        this.btnSave.setEnabled(false);
  
    }                                         

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {                                        
      this.dispose();
    }                                       

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {                                          
        //模糊查询
        String condition = this.txtCondition.getText().trim();
        List<Purchase>listp = pbiz.findByCondition(condition,0);
        List<BaseStore> listb = bsbiz.findByCondition(condition,0);
        showOnTable(listp,listb);
    }                                         

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {                                         
         FrameUtil.framemap.remove(PurchaseToStore.class.getName());
    }                                        

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void txtPidActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void txtBidActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      
     public void clearInput(){
        this.txtEid.setText("");
        this.txtDate.setText("");
        this.txtPid.setText("");
        this.txtGid.setText("");
        this.txtBid.setText("");
        this.txtGnum.setText("");

    }
    public void showOnTable(List<Purchase> listp,List<BaseStore> listb){
        //获取制定（tblProduct）表格模型
        DefaultTableModel dtm = (DefaultTableModel) this.tblProduct.getModel();
        //2清空表格信息
        while(dtm.getRowCount()>0){
            dtm.removeRow(0);
        }
        for(BaseStore b : listb){
        //显示数据
        for(Purchase p : listp){
            //颜色警戒
            if(b.getGid() == p.getGid()){
                Vector vt = new Vector();
                vt.add(p.getEid());
                vt.add(p.getGid());
                vt.add(p.getSid());
                vt.add(p.getGnum());
                vt.add(p.getPurdate());
                vt.add(b.getBid());
                dtm.addRow(vt);
            }
            }
        }
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTextField txtBid;
    private javax.swing.JTextField txtCondition;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEid;
    private javax.swing.JTextField txtGid;
    private javax.swing.JTextField txtGnum;
    private javax.swing.JTextField txtPid;
    // End of variables declaration                   
}
