/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Biz.BaseStoreBiz;
import Biz.BaseStoreBizImpl;
import Biz.RackStoreBiz;
import Biz.RackStoreBizImpl;
import Biz.TransferBiz;
import Biz.TransferBizImpl;
import Dao.DBLink;
import OperateTarget.BaseStore;
import OperateTarget.Employee;
import OperateTarget.RackStore;
import OperateTarget.Transfer;
import Util.*;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class RackToBase extends javax.swing.JInternalFrame {
     //引入biz
    public static Employee user = LoginFrame.user;
    BaseStoreBiz pbiz = new BaseStoreBizImpl();
    RackStoreBiz rbiz = new RackStoreBizImpl();
    TransferBiz tbiz = new TransferBizImpl();
    private Object JoptionPane;
    /**
     * Creates new form ProductFrame
     */
    public RackToBase() {
        initComponents();
        //初始化保存和删除按钮按钮
        this.btnSave.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jComboBox4 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtRid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtGnum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTdate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtBid = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        txtCondition = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setTitle("货架转回库存");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "货架编号", "商品编号", "仓库编号", "商品数量", "转移日期"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduct);

        jLabel2.setText("货架编号");

        jLabel10.setForeground(new java.awt.Color(255, 51, 51));

        jLabel4.setText("商品数量");

        jLabel6.setText("商品编号");

        jLabel8.setText("转移日期");

        txtTdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTdateActionPerformed(evt);
            }
        });

        jLabel9.setText("仓库编号");

        txtBid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtGnum, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(194, 194, 194))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtRid, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtGid, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTdate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtBid, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtBid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtGid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtRid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtTdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtGnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        btnUpdate.setText("更新");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setText("保存");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("取消");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnExit.setText("退出");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnAdd.setText("新增");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSearch.setText("查询");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(487, 487, 487)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnSearch)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnSave)
                    .addComponent(btnCancel)
                    .addComponent(btnExit))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void tblProductMouseClicked(java.awt.event.MouseEvent evt) {                                        
        //鼠标选中某行，改行信息显示到输出面板
        int row = this.tblProduct.getSelectedRow();
        //根据row获取每列的值
        this.txtBid.setText(this.tblProduct.getValueAt(row, 2)+"");
        this.txtGid.setText(this.tblProduct.getValueAt(row, 1) +"");
        this.txtRid.setText(this.tblProduct.getValueAt(row, 0)+"");
        this.txtGnum.setText(this.tblProduct.getValueAt(row, 3)+"");
        this.txtTdate.setText(this.tblProduct.getValueAt(row,4)+"");
        //保存删除按钮可用
        this.btnSave.setEnabled(true);

    }                                       

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {                                          
       //查询数据库将数据显示到表格上
        List<BaseStore> listb = pbiz.findAll();
        List<RackStore> listr = rbiz.findAll();
        List<Transfer> listt = tbiz.findAll();
        //显示list中的信息
        showOnTable(listb,listr,listt);
    }                                         

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {                                       
        //1获取商品信息
        SimpleDateFormat sfd = new SimpleDateFormat("yy-mm-dd");
        int bid = Integer.parseInt(this.txtBid.getText());
        int rid = Integer.parseInt(this.txtRid.getText());
        int gid = Integer.parseInt(this.txtGid.getText());
        int gnum = Integer.getInteger(this.txtGnum.getText());
        Date dt = null;
        try {
            dt = sfd.parse(this.txtTdate.getText());
        } catch (ParseException ex) {
            Logger.getLogger(RackToBase.class.getName()).log(Level.SEVERE, null, ex);
        }
        //数据格式验证使用StringUtil
        //1验证非空
        try{
        //数字格式验证
             if(bid == 0){
                JOptionPane.showMessageDialog(this, "仓库编号为空");
                return;
            }
            if(rid == 0){
                JOptionPane.showMessageDialog(this, "仓库编号为空");
                return;
            }
            if(gid == 0){
                JOptionPane.showMessageDialog(this, "仓库编号为空");
                return;
            }
            if(gnum == 0){
                JOptionPane.showMessageDialog(this, "仓库编号为空");
                return;
            }
            if(dt == null){
                JOptionPane.showMessageDialog(this, "仓库编号为空");
                return;
            }
        }catch(Exception e){
            return;
        }
        DBLink lk = new DBLink();
        Connection conn = lk.getConnection();
        RackStore p = new RackStore();
        BaseStore t = new BaseStore();
        Transfer q = new Transfer();
        t.setBid(bid);
        t.setGid(gid);
        t.setGnum(gnum);
        p.setGid(gid);
        p.setGnum(gnum);
        p.setGid(rid);
        q.setBid(bid);
        q.setGid(gid);
        q.setGnum(gnum);
        q.setRid(rid);
        q.setEid(user.getEid());
        boolean result = false;
        try {
            result = pbiz.add(conn,t);
            result = rbiz.add(conn, p);
            result = tbiz.add(conn, q);
        } catch (SQLException ex) {
            Logger.getLogger(RackToBase.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try {
                conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(RackToBase.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        //清空面板信息
        clearInput();
    }                                      

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {                                        
        //1获取商品信息
        SimpleDateFormat sdf= new SimpleDateFormat("yy-mm-dd");
        int rid = Integer.parseInt(this.txtRid.getText());
        int gid = Integer.parseInt(this.txtGid.getText());
        int bid = Integer.parseInt(this.txtBid.getText());
        int gnum = Integer.parseInt(this.txtGnum.getText());
        Date dt = null;
        try {
            dt = sdf.parse(this.txtTdate.getText());
        } catch (ParseException ex) {
            Logger.getLogger(RackToBase.class.getName()).log(Level.SEVERE, null, ex);
        }
        //数据格式验证使用StringUtil
        //1验证非空
        try{
             if(bid == 0){
                JOptionPane.showMessageDialog(this, "仓库编号为空");
                return;
            }
            if(rid == 0){
                JOptionPane.showMessageDialog(this, "仓库编号为空");
                return;
            }
            if(gid == 0){
                JOptionPane.showMessageDialog(this, "仓库编号为空");
                return;
            }
            if(gnum == 0){
                JOptionPane.showMessageDialog(this, "仓库编号为空");
                return;
            }
            if(dt == null){
                JOptionPane.showMessageDialog(this, "仓库编号为空");
                return;
            }
        }catch(Exception e){
            return;
        }
        DBLink lk = new DBLink();
        Connection conn = lk.getConnection();
        RackStore p = new RackStore();
        BaseStore t = new BaseStore();
        Transfer q = new Transfer();
        t.setBid(bid);
        t.setGid(gid);
        t.setGnum(gnum);
        p.setGid(gid);
        p.setGnum(gnum);
        p.setGid(rid);
        q.setBid(bid);
        q.setGid(gid);
        q.setGnum(gnum);
        q.setRid(rid);
        q.setEid(user.getEid());
        boolean result = false;
        try {
            result = pbiz.update(conn,t);
            result = rbiz.add(conn, p);
            result = tbiz.add(conn, q);
        } catch (SQLException ex) {
            Logger.getLogger(RackToBase.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try {
                conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(RackToBase.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        if(result == true){
            JOptionPane.showMessageDialog(this, "修改成功");
            List<BaseStore> listb = pbiz.findAll();
            List<RackStore> listr = rbiz.findAll();
            List<Transfer> listt = tbiz.findAll();
            showOnTable(listb,listr,listt);
        }else{
            JOptionPane.showMessageDialog(this, "修改失败");
        }
        //清空面板信息
        clearInput();
    }                                       

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {                                          
        //界面恢复到最初状态
        clearInput();
        this.btnSave.setEnabled(false);
    }                                         

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {                                        
      this.dispose();
    }                                       

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {                                          
        //模糊查询
        String condition = this.txtCondition.getText().trim();
        List<BaseStore> listb = pbiz.findByCondition(condition,0);
        List<RackStore> listr  = rbiz.findByCondition(condition,0);
        List<Transfer> listt = tbiz.findAll();
        showOnTable(listb,listr,listt);
    }                                         

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {                                         
         FrameUtil.framemap.remove(RackToBase.class.getName());
    }                                        

    private void txtTdateActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void txtBidActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      
     public void clearInput(){
        this.txtRid.setText("");
        this.txtBid.setText("");
        this.txtGid.setText("");
        this.txtGnum.setText("");
        this.txtTdate.setText("");
    }
    public void showOnTable(List<BaseStore> listb,List<RackStore> listr,List<Transfer> tlist){
        //获取制定（tblProduct）表格模型
        DefaultTableModel dtm = (DefaultTableModel) this.tblProduct.getModel();
        //2清空表格信息
        while(dtm.getRowCount()>0){
            dtm.removeRow(0);
        }
        //显示数据
        for(Transfer q : tlist){
        for(RackStore t : listr){
        for(BaseStore p : listb){
            //颜色警戒
            if(t.getGid() == p.getGid() && q.getGid() == t.getGid() && q.getRid() == t.getRid() && q.getBid() == p.getBid()){
            Vector vt = new Vector();
            vt.add(t.getRid());
            vt.add(p.getGid());
            vt.add(p.getBid());
            vt.add(p.getGnum());
            vt.add(q.getTransdate());
            dtm.addRow(vt);
            }
         }
        }
        }
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTextField txtBid;
    private javax.swing.JTextField txtCondition;
    private javax.swing.JTextField txtGid;
    private javax.swing.JTextField txtGnum;
    private javax.swing.JTextField txtRid;
    private javax.swing.JTextField txtTdate;
    // End of variables declaration                   
}
