/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Biz.RackBiz;
import Biz.RackBizImpl;
import Dao.DBLink;
import OperateTarget.Rack;
import Util.*;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class RackADCS extends javax.swing.JInternalFrame {
     //引入biz
    RackBiz pbiz = new RackBizImpl();
    private Object JoptionPane;
    /**
     * Creates new form ProductFrame
     */
    public RackADCS() {
        initComponents();
        //初始化保存和删除按钮按钮
        this.btnSave.setEnabled(false);
        this.btnDelete.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jComboBox4 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtRid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtRaddr = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        txtCondition = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setTitle("货架资料管理");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "货架编号", "货架地址"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduct);

        jLabel2.setText("货架编号");

        jLabel8.setText("货架地址");

        jLabel10.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtRid, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtRaddr)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(194, 194, 194))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtRaddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        btnUpdate.setText("更新");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setText("保存");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("取消");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnDelete.setText("删除");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnExit.setText("退出");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnAdd.setText("新增");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSearch.setText("查询");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(415, 415, 415)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnSearch)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnSave)
                    .addComponent(btnCancel)
                    .addComponent(btnDelete)
                    .addComponent(btnExit))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void tblProductMouseClicked(java.awt.event.MouseEvent evt) {                                        
        //鼠标选中某行，改行信息显示到输出面板
        int row = this.tblProduct.getSelectedRow();
        //根据row获取每列的值
        this.txtRid.setText(this.tblProduct.getValueAt(row, 0)+"");
        this.txtRaddr.setText(this.tblProduct.getValueAt(row, 1)+"");

        //保存删除按钮可用
        this.btnSave.setEnabled(true);
        this.btnDelete.setEnabled(true);
    }                                       

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {                                          
       //查询数据库将数据显示到表格上
        List<Rack> list = pbiz.findAll();
        //显示list中的信息
        showOnTable(list);
    }                                         

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {                                       
        //1获取商品信息

        int rid = Integer.parseInt(this.txtRaddr.getText().trim());
        String raddr = this.txtRaddr.getText().trim();
        //数据格式验证使用StringUtil
        //1验证非空
        try{
            if(rid == 0){
                JOptionPane.showMessageDialog(this, "供应商电话为空");
                return;
            }
            if(StringUtil.checkLength(raddr) == false){
                JOptionPane.showMessageDialog(this, "供应商电话为空");
                return;
            }

        }catch(Exception e){
            return;
        }

        Rack p = new Rack();
        p.setRaddr(raddr);
        p.setRid(rid);
        DBLink lk = new DBLink();
        
        boolean result = false;
        Connection conn = lk.getConnection();
        try {
            result = pbiz.add(conn,p);
        } catch (SQLException ex) {
            Logger.getLogger(RackADCS.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try {
                conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(RackADCS.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(result == true){
            JOptionPane.showMessageDialog(this, "添加成功");
            List<Rack>list = pbiz.findAll();
            showOnTable(list);
        }else{
            JOptionPane.showMessageDialog(this, "添加失败");
        }
        //清空面板信息
        clearInput();
    }                                      

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {                                          
        int answer = JOptionPane.showConfirmDialog(this, "您确定要删除吗？");
        if(answer == JOptionPane.YES_OPTION){
            int proid = Integer.parseInt(this.txtRid.getText());
            DBLink lk = new DBLink();
            Connection conn = lk.getConnection();
            boolean result = false;
            try {
                result = result = pbiz.delete(conn,proid);
            } catch (SQLException ex) {
                Logger.getLogger(RackADCS.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                try {
                    conn.close();
                } catch (SQLException ex) {
                    Logger.getLogger(RackADCS.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(result){
                JOptionPane.showMessageDialog(this, "删除成功");
                List<Rack>list = pbiz.findAll();
                //显示list中的信息
                showOnTable(list);
            }else{
                JOptionPane.showMessageDialog(this, "删除失败");
            }
        }
    }                                         

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {                                        
        //1获取商品信息
        int rid = Integer.parseInt(this.txtRaddr.getText().trim());
        String raddr = this.txtRaddr.getText().trim();

        //数据格式验证使用StringUtil
        //1验证非空
        try{
            if(rid == 0){
                JOptionPane.showMessageDialog(this, "供应商电话为空");
                return;
            }
            if(StringUtil.checkLength(raddr) == false){
                JOptionPane.showMessageDialog(this, "供应商电话为空");
                return;
            }
        }catch(Exception e){
            return;
        }
  
        Rack p = new Rack();
        p.setRaddr(raddr);
        p.setRid(rid);
        DBLink lk = new DBLink();
        Connection conn = lk.getConnection();
        boolean result = false;
        try {
            result = pbiz.update(conn,p);
        } catch (SQLException ex) {
            Logger.getLogger(RackADCS.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            try {
                conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(RackADCS.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(result == true){
            JOptionPane.showMessageDialog(this, "修改成功");
            List<Rack>list = pbiz.findAll();
            showOnTable(list);
        }else{
            JOptionPane.showMessageDialog(this, "修改失败");
        }
        //清空面板信息
        clearInput();
    }                                       

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {                                          
        //界面恢复到最初状态
        clearInput();
        this.btnSave.setEnabled(false);
        this.btnDelete.setEnabled(false);
    }                                         

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {                                        
      this.dispose();
    }                                       

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {                                          
        //模糊查询
        String condition = this.txtCondition.getText().trim();
        List<Rack>list = pbiz.findByCondition(condition);
        showOnTable(list);
    }                                         

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {                                         
         FrameUtil.framemap.remove(RackADCS.class.getName());
    }                                        
     public void clearInput(){
        this.txtRid.setText("");

    }
    public void showOnTable(List<Rack> list){
        //获取制定（tblProduct）表格模型
        DefaultTableModel dtm = (DefaultTableModel) this.tblProduct.getModel();
        //2清空表格信息
        while(dtm.getRowCount()>0){
            dtm.removeRow(0);
        }
        //显示数据
        for(Rack p : list){
            //颜色警戒
            Vector vt = new Vector();
            vt.add(p.getRid());
            vt.add(p.getRaddr());
            dtm.addRow(vt);
        }
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTextField txtCondition;
    private javax.swing.JTextField txtRaddr;
    private javax.swing.JTextField txtRid;
    // End of variables declaration                   
}
