package view;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Biz.GoodsBiz;
import Biz.GoodsBizImpl;
import Biz.PurchaseBiz;
import Biz.PurchaseBizImpl;
import OperateTarget.Goods;
import OperateTarget.Purchase;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import Util.*;
/**
 *
 * @author Administrator
 */
public class SinglePurchaseSearch extends javax.swing.JInternalFrame {
    GoodsBiz vbiz = new GoodsBizImpl();
    PurchaseBiz pbiz = new PurchaseBizImpl();
    /**
     * Creates new form InventorySearchFrame
     */
    public SinglePurchaseSearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        btnSearch = new javax.swing.JButton();
        txtCondition = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStorecount = new javax.swing.JTable();
        btnExit = new javax.swing.JButton();

        setClosable(true);
        setTitle("单件商品采购表");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        btnSearch.setText("查询");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblStorecount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "员工编号", "商品编号", "供应商编号", "商品数量", "购入日期", "商品名称", "购入价格"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblStorecount);

        btnExit.setText("退出");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(562, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnExit)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(txtCondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>                        
//"商品编号", "商品名称", "类型", "容量", "接口类型", "库存"商品编号", "商品名称", "当前库存", "建议采购价", "最近采购日期", "建议销售价", "最近销售日期"
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        String condition = this.txtCondition.getText().trim();
        List<Goods> listg = vbiz.findByCondition(condition, 0);
        List<Purchase> listp = pbiz.findByCondition(condition,0);
        showOnTable(listp,listg);
    }                                         

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        this.dispose();
    }                                       

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {                                         
        FrameUtil.framemap.remove(AllPurchase.class.getName());
    }                                        
private void showOnTable(List<Purchase> listp,List<Goods> listg) {
        //1 获得表格模型
        DefaultTableModel dtm = (DefaultTableModel) this.tblStorecount.getModel();
        //2 清空表格
        while(dtm.getRowCount()>0){
            dtm.removeRow(0);
         }
        Goods temp = listg.get(0);
        // 3添加到表格
        for(Purchase p: listp){
            Vector vt = new Vector();
            vt.add(p.getEid());
            vt.add(p.getGid());
            vt.add(p.getSid());
            vt.add(p.getGnum());
            vt.add(p.getPurdate());
            vt.add(temp.getGname());
            vt.add(temp.getGpprice());
            dtm.addRow(vt);
        }
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStorecount;
    private javax.swing.JTextField txtCondition;
    // End of variables declaration                   
}
